# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_version_number(
      bump_type: "patch"
    )
    increment_build_number
    commit_version_bump
    add_git_tag
    push_to_git_remote
    build_app(scheme: "ZenTuner_iOS")
    upload_to_testflight
  end
end
